#!/usr/bin/env bash
set -euo pipefail

# === Config ===
readonly GIT_REPO_PATH="$(cd "$(dirname "$0")" && pwd)"
readonly VERSION_FILE="$GIT_REPO_PATH/version"
readonly CHANGELOG_FILE="$GIT_REPO_PATH/CHANGELOG.md"

# === Output helpers ===
say()  { printf '%s\n' "$*"; }
warn() { printf '[⚠️] %s\n' "$*" >&2; }
die()  { printf '[❌] %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: $0 [version]

Creates a GitHub release for the given version, using the matching
CHANGELOG.md section as release notes.

  $0            Use version from ./version
  $0 2.0.1      Release v2.0.1 explicitly
EOF
  exit 1
}

# Print the body of a CHANGELOG section (no heading line, macOS/BSD-safe).
extract_release_notes() {
  local version="$1"
  awk -v header="## [$version]" '
    index($0, header) == 1 { capture = 1; next }   # skip the heading itself
    capture && /^## \[/    { exit }
    capture                { print }
  ' "$CHANGELOG_FILE" | sed '/./,$!d'              # drop leading blank lines
}

# === Pre-flight checks ===
command -v gh &>/dev/null || die "GitHub CLI 'gh' not found.
    Install: https://cli.github.com  (Ubuntu: sudo apt install gh)"

gh auth status &>/dev/null || die "GitHub CLI is not authenticated.
    Run: gh auth login"

cd "$GIT_REPO_PATH"

# === Determine version ===
case $# in
  0)
    [[ -f "$VERSION_FILE" ]] || die "No version file at $VERSION_FILE"
    VERSION=$(<"$VERSION_FILE")
    ;;
  1)
    [[ "$1" == "-h" || "$1" == "--help" ]] && usage
    VERSION="${1#v}"
    ;;
  *)
    usage
    ;;
esac
VERSION="${VERSION//[[:space:]]/}"
TAG="v$VERSION"

# === Verify tag exists locally ===
git rev-parse "$TAG" >/dev/null 2>&1 || die "Tag $TAG does not exist locally.
    Run ./update-version.sh patch|minor|major to create it."

# === Push tag if missing on remote ===
if ! git ls-remote --tags origin "refs/tags/$TAG" | grep -q "$TAG"; then
  warn "Tag $TAG is not on origin yet."
  read -rp "Push tag to origin now? (y/n): " push_choice
  if [[ "$push_choice" == "y" ]]; then
    git push origin "$TAG"
  else
    die "Aborting — release needs the tag pushed."
  fi
fi

# === Don't double-create ===
if gh release view "$TAG" &>/dev/null; then
  warn "Release $TAG already exists on GitHub."
  gh release view "$TAG" --json url -q .url
  exit 1
fi

# === Extract changelog block for this version ===
NOTES=$(extract_release_notes "$VERSION")

USE_AUTO_NOTES=false
if [[ -z "${NOTES//[[:space:]]/}" ]]; then
  warn "No changelog entry found for $VERSION in CHANGELOG.md"
  read -rp "Use auto-generated release notes from commits? (y/n): " auto_choice
  [[ "$auto_choice" == "y" ]] || exit 1
  USE_AUTO_NOTES=true
fi

# === Preview ===
say ""
say "[📋] Release preview"
say "    Tag:   $TAG"
say "    Title: $TAG"
say "    Notes:"
if $USE_AUTO_NOTES; then
  say "      (auto-generated by gh from commits)"
else
  printf '%s\n' "$NOTES" | sed 's/^/      /'
fi
say ""

read -rp "Create this release? (y/n): " confirm
if [[ "$confirm" != "y" ]]; then
  say "[ℹ️] Aborted."
  exit 0
fi

# === Create release ===
if $USE_AUTO_NOTES; then
  gh release create "$TAG" --title "$TAG" --generate-notes
else
  gh release create "$TAG" --title "$TAG" --notes "$NOTES"
fi

say "[🚀] Release $TAG created."