#!/bin/bash
set -euo pipefail

# === Config ===
GIT_REPO_PATH="$(cd "$(dirname "$0")" && pwd)"
VERSION_FILE="$GIT_REPO_PATH/version"
CHANGELOG_FILE="$GIT_REPO_PATH/CHANGELOG.md"

usage() {
  cat <<EOF
Usage: $0 [version]

Creates a GitHub release for the given version, using the matching
CHANGELOG.md section as release notes.

  $0            Use version from ./version
  $0 2.0.1      Release v2.0.1 explicitly
EOF
  exit 1
}

# === Pre-flight checks ===
if ! command -v gh &>/dev/null; then
  echo "[❌] GitHub CLI 'gh' not found."
  echo "    Install: https://cli.github.com  (Ubuntu: sudo apt install gh)"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "[🔐] GitHub CLI is not authenticated."
  echo "    Run: gh auth login"
  exit 1
fi

cd "$GIT_REPO_PATH"

# === Determine version ===
case $# in
  0)
    if [[ ! -f "$VERSION_FILE" ]]; then
      echo "[❌] No version file at $VERSION_FILE"
      exit 1
    fi
    VERSION=$(<"$VERSION_FILE")
    ;;
  1)
    [[ "$1" == "-h" || "$1" == "--help" ]] && usage
    VERSION="${1#v}"
    ;;
  *)
    usage
    ;;
esac

TAG="v$VERSION"

# === Verify tag exists locally ===
if ! git rev-parse "$TAG" >/dev/null 2>&1; then
  echo "[❌] Tag $TAG does not exist locally."
  echo "    Run ./update-version.sh patch|minor|major to create it."
  exit 1
fi

# === Push tag if missing on remote ===
if ! git ls-remote --tags origin "refs/tags/$TAG" | grep -q "$TAG"; then
  echo "[⚠️] Tag $TAG is not on origin yet."
  read -rp "Push tag to origin now? (y/n): " push_choice
  if [[ "$push_choice" == "y" ]]; then
    git push origin "$TAG"
  else
    echo "[ℹ️] Aborting — release needs the tag pushed."
    exit 1
  fi
fi

# === Don't double-create ===
if gh release view "$TAG" &>/dev/null; then
  echo "[⚠️] Release $TAG already exists on GitHub."
  gh release view "$TAG" --json url -q .url
  exit 1
fi

# === Extract changelog block for this version ===
NOTES=$(sed -n "/^## \[$VERSION\]/,/^## \[/p" "$CHANGELOG_FILE")
if [[ $(tail -n 1 <<< "$NOTES") =~ ^##\ \[ ]]; then
  NOTES=$(head -n -1 <<< "$NOTES")
fi
# Drop the version heading line — title already shows it
NOTES=$(tail -n +2 <<< "$NOTES" | sed '/./,$!d')

USE_AUTO_NOTES=false
if [[ -z "${NOTES//[[:space:]]/}" ]]; then
  echo "[⚠️] No changelog entry found for $VERSION in CHANGELOG.md"
  read -rp "Use auto-generated release notes from commits? (y/n): " auto_choice
  if [[ "$auto_choice" != "y" ]]; then
    exit 1
  fi
  USE_AUTO_NOTES=true
fi

# === Preview ===
echo
echo "[📋] Release preview"
echo "    Tag:   $TAG"
echo "    Title: $TAG"
echo "    Notes:"
if $USE_AUTO_NOTES; then
  echo "      (auto-generated by gh from commits)"
else
  echo "$NOTES" | sed 's/^/      /'
fi
echo

read -rp "Create this release? (y/n): " confirm
if [[ "$confirm" != "y" ]]; then
  echo "[ℹ️] Aborted."
  exit 0
fi

# === Create release ===
if $USE_AUTO_NOTES; then
  gh release create "$TAG" --title "$TAG" --generate-notes
else
  gh release create "$TAG" --title "$TAG" --notes "$NOTES"
fi

echo "[🚀] Release $TAG created."
